export const getViewer360Props = (element: HTMLElement) => ({
  folder: element.dataset.folder || '/',
  filename: element.dataset.filename || 'image-{index}.jpg',
  amount: parseInt(element.dataset.amount || String(36), 10),
  speed: parseInt(element.dataset.speed || String(80), 10),
  swipeable: element.dataset.swipeable ? !!Boolean(element.dataset.swipeable) : true,
  draggable: element.dataset.draggable ? !!Boolean(element.dataset.draggable) : true,
  dragSpeed: parseInt(element.dataset.dragSpeed || String(150), 10),
  keys: !!element.dataset.keys,
  autoplay: !!element.dataset.autoplay,
  autoplayReverse: !!element.dataset.autoplayReverse,
  ratio: parseFloat(element.dataset.ratio || String(0)) || 0,
  responsive: !!element.dataset.responsive,
  lazyload: !!element.dataset.lazyload,
  lazySelector: element.dataset.lazyloadSelector || 'lazyload',
  spinReverse: !!element.dataset.spinReverse,
  controlReverse: !!element.dataset.controlReverse,
  stopAtEdges: !!element.dataset.stopAtEdges,
})
